repos:
- repo: local
  hooks:
    - id: ruff-fix
      name: Linting with Automatic Fixes
      entry: .github/workflows/ruff.sh
      args:
        - check
        - --fix
      language: system
      pass_filenames: false
    - id: ruff-format
      name: Formatting
      entry: .github/workflows/ruff.sh
      args:
        - format
      language: system
      pass_filenames: false 